registry:
  restart: always
  image: registry:2
  ports:
    - 5555:5000
  expose:
    - 5555
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.pem
    REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: basic
    REGISTRY_AUTH_HTPASSWD_PATH: /certs/htpasswd
    REGISTRY_STORAGE_DELETE_ENABLED: "true"
    REGISTRY_STORAGE: s3
    REGISTRY_STORAGE_S3_ACCESSKEY: myAccessKey
    REGISTRY_STORAGE_S3_SECRETKEY: mySecretKey
    REGISTRY_STORAGE_S3_BUCKET: myBucket
    REGISTRY_STORAGE_S3_REGION: us-east-1
    REGISTRY_STORAGE_S3_REGIONENDPOINT: storagegridgw
    REGISTRY_STORAGE_S3_SECURE: "true"
    REGISTRY_STORAGE_S3_V4AUTH: "true"
    REGISTRY_STORAGE_S3_CHUNKSIZE: 5242880
    REGISTRY_STORAGE_S3_MULTIPARTCOPYCHUNKSIZE: 33554432
    REGISTRY_STORAGE_S3_MULTIPARTCOPYMAXCONCURRENCY: 100
    REGISTRY_STORAGE_S3_MULTIPARTCOPYTHRESHOLDSIZE: 33554432
    REGISTRY_CACHE_blobdescriptor: inmemory
    REGISTRY_HTTP_ADDR: localhost:5000
    REGISTRY_HTTP_HEADERS: "X-Content-Type-Options: [nosniff]"
    REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: "false"
    REGISTRY_HEALTH_STORAGEDRIVER_INTERVAL: 10s
    REGISTRY_HEALTH_STORAGEDRIVER_THRESHOLD: 3
  volumes:
    - ./sslkeys:/certs
