version: 0.1
log:
  fields:
      service: registry
storage:
  s3:
    accesskey: my access key
    secretkey: my secret key
    region: us-east-1
    bucket: my bucket name
    regionendpoint: my storageGRID gateway or storage node
    secure: true
    v4auth: true
    chunksize: 5242880
    multipartcopychunksize: 33554432
    multipartcopymaxconcurrency: 100
    multipartcopythresholdsize: 33554432
  cache:
    blobdescriptor: inmemory
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: false
    interval: 10s
    threshold: 3
